### ISSUE TITLE
# step 3: Divide the DLs into files containing 250 entries

### ISSUE THREAD

**Issue by EBU34rf34** [orchardl/DLUsage#1]
partial division will not be included in the output file: ~\DLgroup$i.txt

e.g. 1312 DL's
split between 5 x DLs (of 250 each = 1250 DL's) but last 62 DL's will not be included

I'm sure there's a more elegant way of doing it, but I just split my total DL's into an integer that was below 250. e.g. in this case 1312/8 = 164 (8 x DL batches with 164 DL's in each)

**Comment by orchardl** [comment]
Good catch! Thank you for bringing this to my attention. When I first wrote this, totally by chance, the data I was using for testing had 750 DLs, so I didn't even consider this. 

I've added the below code at the end of step 3 to resolve this. I've tested step 3 and it appears to be working as expected now:)
```
$remainder = (Get-Content -Path ~\DLs.txt).length % 250
if ($remainder -ne 0) {
	$numfiles = $numfiles + 1
	Get-Content -tail $remainder -Path ~\DLs.txt > ~\DLgroup$numfiles.txt
}
```
